### ISSUE TITLE
Some known Lotus file formats not listed in convert_map.json

### ISSUE THREAD

**Issue by felix0908** [aarhusstadsarkiv/symphovert#68]
Here's the list of the ones seemingly missing. They're all spreadsheet formats, and they're all different versions of Lotus worksheet.

x-fmt/114 
Lotus 1-2-3 Worksheet 2.0

x-fmt/115
Lotus 1-2-3 Worksheet 3.0

x-fmt/116
Lotus 1-2-3 Worksheet 4-5

x-fmt/117
Lotus 1-2-3 Worksheet 1.0

**Comment by clausjuhl** [comment]
These fileformats are nowconverted with libreconverter.
